version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "monthly"
      day: monday
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    labels:
      - "dependencies"
    versioning-strategy: "auto"
